course/urls.py
'''
=====================================================================
Copyright (C) 2019 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of webMCTest 1.1 (or MCTest 5.1).

Languages: Python 3.7, Django 2.2.4 and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br:8000
in any publication about it.

webMCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

webMCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    # path('institute', IndexTemplateView.as_view(), name="index"),
    path('institutes/', views.InstituteListView.as_view(), name='institute-list'),
    path('institute/create/', views.InstituteCreate.as_view(), name='institute-create'),
    path('institute/<int:pk>/', views.InstituteDetailView.as_view(), name='institute-detail'),
    path('institute/<int:pk>/delete/', views.InstituteDelete.as_view(), name='institute-delete'),
    path('institute/<int:pk>/update', views.InstituteUpdate.as_view(), name='institute-update'),
]

urlpatterns += [
    path('courses/', views.CourseListView.as_view(), name='course-list'),
    path('course/create/', views.CourseCreate.as_view(), name='course-create'),
    path('course/<int:pk>/', views.CourseDetailView.as_view(), name='course-detail'),
    path('course/<int:pk>/delete/', views.CourseDelete.as_view(), name='course-delete'),
    path('course/<int:pk>/update', views.CourseUpdate.as_view(), name='course-update'),
]

urlpatterns += [
    path('disciplines/', views.DisciplineListView.as_view(), name='discipline-list'),
    path('discipline/create/', views.DisciplineCreate.as_view(), name='disciplines-create'),
    path('discipline/<int:pk>/', views.DisciplineDetailView.as_view(), name='discipline-detail'),
    path('discipline/<int:pk>/delete/', views.DisciplineDelete.as_view(), name='discipline-delete'),
    path('discipline/<int:pk>/update', views.DisciplineUpdate.as_view(), name='discipline-update'),
    path('discipline/<int:pk>/import/', views.ImportProfsDiscipline, name='discipline-profs-import'),
    path('discipline/<int:pk>/import2/', views.ImportClassroomsDiscipline, name='discipline-classrooms-import'),
]

urlpatterns += [
    # path('classrooms/',               views.ClassroomListView.as_view(), name=''),
    path('classroomsmy/', views.LoanedClassroomByUserListView.as_view(), name='classroom-mylist'),
    path('classroom/create/', views.ClassroomCreate.as_view(), name='classroom-create'),
    path('classroom/<int:pk1>/student/<int:pk2>/delete', views.ClassroomStudentDelete, name='classroom-student-delete'),
    # path('classroom/<int:pk>/student/create', views.ClassroomStudentCreate, name='classroom-student-create'),
    path('classroom/<int:pk>', views.ClassroomDetailView.as_view(), name='classroom-detail'),
    path('classroom/<int:pk>/delete/', views.ClassroomDelete.as_view(), name='classroom-delete'),
    path('classroom/<int:pk>/update', views.ClassroomUpdate.as_view(), name='classroom-update'),
    path('classroom/<int:pk>/import/', views.ImportStudentsClassroom, name='classroom-students-import'),
]

exam/urls.py
'''
=====================================================================
Copyright (C) 2019 Francisco de Assis Zampirolli
from Federal University of ABC and individual contributors.
All rights reserved.

This file is part of webMCTest 1.1 (or MCTest 5.1).

Languages: Python 3.7, Django 2.2.4 and many libraries described at
github.com/fzampirolli/mctest

You should cite some references included in vision.ufabc.edu.br:8000
in any publication about it.

webMCTest is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License
(gnu.org/licenses/agpl-3.0.txt) as published by the Free Software
Foundation, either version 3 of the License, or (at your option) 
any later version.

webMCTest is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

=====================================================================
'''
from django.urls import path

from . import views

app_name = 'exam'
urlpatterns = [
    path('exams/', views.ExamListView.as_view(), name=''),
    path('myexams/', views.LoanedExamByUserListView.as_view(), name='myexams'),
    path('exam/<int:pk>', views.ExamDetailView.as_view(), name='exam-detail'),
    path('exam/create/', views.ExamCreate.as_view(), name='exam-create'),
    path('exam/<int:pk>/createPDF/', views.SerializersExam, name='exam-createPDF'),
    path('exam/<int:pk>/generate/', views.generate_page, name='generate_page'),
    path('exam/<int:pk>/delete/', views.ExamDelete.as_view(), name='exam-delete'),
    path('exam/<int:pk>/update/', views.UpdateExam, name='exam_update'),
    path('exam/<int:pk>/correct/', views.correctStudentsExam, name='exam-correct'),
    path('exam/<int:pk>/sendFeedbackStudents/', views.feedbackStudentsExam, name='exam-feedback'),
    path('exam/<int:pk>/sendFeedbackStudentsText/', views.feedbackStudentsExamText, name='exam-feedback'),
]

main/urls.py
from account import admin

"""mctest URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import include
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('readme', views.readme, name='readme'),
    path('license', views.license, name='license'),
    path('contributors', views.contributors, name='contributors'),
    path('users', views.users, name='users'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

mctest/urls.py
"""mctest URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import include
from django.contrib import admin
from django.urls import path


from django.conf.urls.static import static

from mctest.settings import STATIC_ROOT
from mctest.settings import STATIC_URL

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('topic/', include('topic.urls'), name='topic'),
    path('exam/', include('exam.urls'), name='exam'),
    path('course/', include('course.urls'), name='course'),
    path('account/', include('django.contrib.auth.urls')),
    path('student/', include('student.urls'), name='student'),
] + static(STATIC_URL, document_root=STATIC_ROOT)

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import UpdateView, DeleteView
from account.forms import UserCreateForm
from django.urls import reverse_lazy
from account.models import User
from course.models import Institute, Course, Classroom, Discipline
from topic.models import Topic, Question, Answer
from exam.models import Exam

# Create your views here.


class SignUp(generic.CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

######################################
from django.contrib.sessions.models import Session
from django.utils import timezone


def contributors(request):
    return render(request, 'contributors.html', {})

def users(request):
    return render(request, 'users.html', {})


def readme(request):
    return render(request, 'readme.html', {})


def license(request):
    return render(request, 'license.html', {})


def index(request):
    users = User.objects.order_by('-last_login')[:10]  # all list 10 last users-login

    # all users logged now
    # Session.objects.all().delete()
    sessions = Session.objects.filter(expire_date__gte=timezone.now())
    uid_list = []
    for session in sessions:
        data = session.get_decoded()
        uid_list.append(data.get('_auth_user_id', None))
    users_now = User.objects.filter(id__in=uid_list)

    num_institutes = Institute.objects.all().count()
    num_courses = Course.objects.all().count()
    num_disciplines = Discipline.objects.all().count()
    num_classrooms = Classroom.objects.all().count()

    num_exams = Exam.objects.all().count()

    num_users = User.objects.all().count()

    num_questions = Question.objects.all().count()
    num_topics = Topic.objects.all().count()
    num_QM = Question.objects.filter(question_type='QM').count()
    num_QT = Question.objects.filter(question_type='QT').count()
    num_Parametric = Question.objects.filter(question_parametric='yes').count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(request, 'index.html',
                  context={'num_institutes': num_institutes,
                           'num_courses': num_courses,
                           'num_disciplines': num_disciplines,
                           'num_classrooms': num_classrooms,
                           'num_questions': num_questions,
                           'num_topics': num_topics,
                           'num_QM': num_QM,
                           'num_QT': num_QT,
                           'num_Parametric': num_Parametric,
                           'num_exams': num_exams,
                           'num_users': num_users,
                           'users_now': users_now,
                           'users': users,
                           'num_visits': num_visits})

main/templates/base_generic.html
{# base_generic.html it's the skeleton model #}
{% load static %}

<!DOCTYPE html>
<html lang="pt">

<head>
    {% load i18n %}
    <!-- Add additional CSS in static file -->
    {% load static %}

    <meta charset="utf-8">

    <!-- Title -->
    {% block title %}<title>webMCTest</title>{% endblock %}

    <!-- Favicon -->
    <link rel="shortcut icon" href="http://vision.ufabc.edu.br/static/webMCTest.png" type="image/png">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


    {% block styles %}{% endblock %}

    <style>
        .carousel-caption {
            position: relative;
            left: 0;
            top: 0;
        }
    </style>
</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'main:index' %}">
        <img src="http://vision.ufabc.edu.br/static/webMCTest.png" height="45px" >
    </a>
    <button class="navbar-toggler" type="button"
            data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav mr-auto">

            <li class="nav-item">
                <a class="nav-link" href="{% url 'course:institute-list' %}">{% trans "All institutes" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'course:course-list' %}">{% trans "All courses" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'course:discipline-list' %}">{% trans "All disciplines" %}</a>
            </li>

            {% if user.is_authenticated and user.groups.all.0.name == 'professor' %}
            <li class="nav-item">
                <a class="nav-link" href="/topic/topics">{% trans "All topics" %}</a>
            </li>

            {% if user.groups.all.0.name == 'professor' %}
            <li class="nav-item">
                <a class="nav-link" href="/topic/questions">{% trans "All questions" %}</a>
            </li>
            {% endif %}

            {% if user.is_staff %}
            <li class="nav-item">
                <a class="nav-link" href="/exam/exams/">{% trans "All exams" %}</a>
            </li>
            <p>
                {% endif %}
                {% endif %}

        </ul>
        <ul class="navbar-nav float-right">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="#">{{ user.username }}:</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="/topic/myquestions/">{% trans "Questions" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/course/classroomsmy/">{% trans "Classrooms" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/exam/myexams/">{% trans "Exams" %}</a>
            </li>
            <p>
                {% if user.is_staff %}
            <li class="nav-item">
                <a class="nav-link" href="/admin">{% trans "Admin" %}</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}?next={{ request.path }}">{% trans "Logout" %}</a>
            </li>

            {% else %}
            <li><a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">{% trans "Login" %}</a></li>
            {% endif %}

            <li class="nav-item">
                <a class="nav-link" href="/signup">{% trans "Sign up" %}</a>
            </li>

        </ul>

    </div>
</nav>

<!-- Contend of site -->
{% block content %}{% endblock %}


{% block scripts %}{% endblock %}

<!-- For scrolls in tables -->
<link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/buttons/1.6.0/css/buttons.bootstrap4.min.css" rel="stylesheet">

<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.bootstrap4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.0/js/buttons.colVis.min.js"></script>

<hr>

<!-- table example -->
<script>
    $(document).ready(function () {
        var table = $('#example').DataTable({
            dom: "Bfrtip",
            scrollY: "550px",
            scrollX: true,
            paging: false,
            //bInfo: false,
            buttons: [
                {
                    extend: 'copy',
                    text: '{% trans 'copy' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'csv',
                    text: '{% trans 'csv' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'excel',
                    text: '{% trans 'excel' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'pdf',
                    text: '{% trans 'pdf' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'print',
                    text: '{% trans 'print' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },

                {
                    extend: 'colvis',
                    text: '{% trans 'column visibility' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
            ]
        });

        table.buttons().container()
            .appendTo('#example_wrapper .col-md-6:eq(0)');
    });

</script>

<!-- table example0 - show classrooms in disciplines detail -->
<script>
    $(document).ready(function () {
        var table = $('#example0').DataTable({
            dom: "Bfrtip",
            scrollY: "550px",
            scrollX: true,
            paging: false,
            //bInfo: false,
            buttons: [
                {
                    extend: 'copy',
                    text: '{% trans 'copy' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'csv',
                    text: '{% trans 'csv' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'excel',
                    text: '{% trans 'excel' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'pdf',
                    text: '{% trans 'pdf' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'print',
                    text: '{% trans 'print' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                //{
                //    extend: 'colvis',
                //    text: '{% trans 'column visibility' %}',
                //    exportOptions: {
                //        columns: ':visible'
                //    }
                //},
            ]
        });

        table.buttons().container()
            .appendTo('#example0_wrapper .col-md-6:eq(0)');
    });
</script>

<!-- table example1 - show exam update -->
<script>
    $('body').on('change', '#mass_select_all', function () {
        var rows, checked;
        rows = $('#example1').find('tbody tr');
        checked = $(this).prop('checked');
        $.each(rows, function () {
            var checkbox = $($(this).find('td').eq(0)).find('input').prop('checked', checked);
        });
    });

    $(document).ready(function () {
        var table = $('#example1').DataTable({
            "columnDefs": [{
                "targets": [0],
                "orderable": false,
            }],
            dom: "Bfrtip",
            scrollY: "550px",
            scrollX: true,
            paging: false,
            //bInfo: false,
            buttons: [
                {
                    extend: 'copy',
                    text: '{% trans 'copy' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'csv',
                    text: '{% trans 'csv' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'excel',
                    text: '{% trans 'excel' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'pdf',
                    text: '{% trans 'pdf' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
                {
                    extend: 'print',
                    text: '{% trans 'print' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },

                {
                    extend: 'colvis',
                    text: '{% trans 'column visibility' %}',
                    exportOptions: {
                        columns: ':visible'
                    }
                },
            ]
        });

        table.buttons().container()
            .appendTo('#example_wrapper .col-md-6:eq(0)');
    });
</script>

<style>
    table.dataTable {
        border-collapse: collapse !important;
    }
</style>


<ul>
  <font size="2" color="black">
        <a href="https://www.gnu.org/licenses/agpl-3.0.html"><img src="http://vision.ufabc.edu.br/static/agplv3.png"></a>
        <a href="{% url 'main:license' %}">Copyright © 2019</a> {%  trans "by" %}
        <a href="https://sites.google.com/site/fzampirolli/">Francisco de Assis Zampirolli</a>
        {%  trans "from" %} <a href="http://www.ufabc.edu.br">{%  trans "Federal University of ABC" %}</a> {%  trans "and" %}
        <a href="{% url 'main:contributors' %}">{%  trans "individual contributors" %}</a>;
        <a href="{% url 'main:users' %}">{%  trans "Who use" %}</a>;
        <a href="http://github.com/fzampirolli/mctest">{%  trans "Download" %}</a>;
        <a href="{% url 'main:readme' %}"> {%  trans "README" %}.</a><br>
    {%  trans "Grant" %}:
    <a href="https://bv.fapesp.br/pt/auxilios/28430/modelagem-de-objetos-usando-morfologia-matematica-e-grafos-de-vizinhanca/">
      #2009/14430–1</a> {%  trans "and" %}
    <a href="https://bv.fapesp.br/pt/auxilios/105047/um-sistema-universal-para-geracao-e-correcao-automatica-de-questoes-parametrizadas/">
      #2018/23561-1</a> - {% trans "São Paulo Research Foundation (FAPESP)" %}.
    
  </font>
</ul>

</body>

</html>

main/templates/contributors.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
    <div class="container mt-5" style="max-width: 87rem;">
        <div class="card">
            <div class="card-body">

                <h5 class="card-title">{% trans "Contributors" %}</h5>

                <hr>

                <ol>
                    <li>
                        {% trans "Thanks to many contributors who provided interesting information and are co-authors of the publications presented at" %}
                        <a href="vision.ufabc.edu.br:8000">vision.ufabc.edu.br:8000</a>.
                    </li>

                    <li>
                        {% trans "We also thank the contributors who helped codify webMCTest, unknown in web discussion forums" %}.
                    </li>

                    <li>
                        {% trans "I think the big difference with webMCTest is the parameterized issue, which may need custom Python functions to make writing easier. In this regard, I also thank" %}
                        (<a href="http://vision.ufabc.edu.br/static/Utils.py">Utils.py</a>):
                    </li>
                    <ul>
                        <li>
                            Jorge Tomioka -  UFABC
                        </li>
                    </ul>
                </ol>

                <hr>

                <p>{% trans "I hope this list grows more and more" %} ...</p>

                {% trans "Please email" %} <a
                    href="mailto:fzampirolli@ufabc.edu.edu">fzampirolli@ufabc.edu.edu</a> {% trans "if I forgot anyone" %}.

            </div>
        </div>
    </div>
{% endblock %}

main/templates/readme.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
    <div class="container mt-5" style="max-width: 87rem;">
        <div class="card">
            <div class="card-body">

                <h5 class="card-title">{% trans "README" %} - mctest v. 5.1 ({% trans "or" %} webMCTest 1.1)</h5>

                <hr>

                <p>{% trans "Welcome to webMCTest, a website devoted to assist in preparing and correcting exams" %}.</p>
                <p>
                    {% trans "WebMCtest is a free open-source software (see" %}
                    <a href="{% url 'main:license' %}">{% trans "License" %}</a>)
                    {% trans "and its best advantage is the handling to parametric questions through LaTeX and Python, allowing for infinite variations of each same question" %}.
                </p>

                <p>
                    {% trans "Please access " %}
                    <a href="http://vision.ufabc.edu.br:8000">vision.ufabc.edu.br:8000</a>
                    {% trans "for some " %}
                    <a href="http://vision.ufabc.edu.br/MCTest/MCTest5-Experiments/">examples</a>.
                    {% trans "Final URL :8000 is for development" %}.

                </p>
                <p>
                <h6>{% trans "Help us spread webMCtest. If more people use it, the faster the improvements" %}.</h6></p>
                <p>{% trans "WebMCtest must be installed on an Ubuntu 18.04 server through ports 3306 and 8000" %}.</p>
                <p>{% trans "Define specific data in the file " %}
                    <a href="http://vision.ufabc.edu.br/static/_settings.env">_settings.env</a>.
                </p>
                <p>
                <h6>
                    {% trans "After downloading in " %}
                    <a href="http://github.com/fzampirolli/mctest">github.com/fzampirolli/mctest</a>
                    {% trans "install webMCTest with" %}:
                </h6>
                <ol>
                <pre>
                    sudo su
                    source _setup_all.sh</pre>
                </ol>

                <p><h5>{% trans "Future Improvements" %}</h5></p>
                <ol>
                    <li>
                        <p>{% trans "Error messages and Graphical interfaces" %};</p>
                    </li>
                    <li>
                        <p>{% trans "Install" %} <a href="http://vision.ufabc.edu.br/static/_setup-all.sh">_setup-all.sh</a>
                            ({% trans "including other operating systems" %});</p>
                    </li>
                    <li>
                        <p>{% trans "The time to generate PDF from an exam with many students" %};</p>
                    </li>
                    <li>
                        <p>{% trans "Site and DB in different languages. For example, edit the " %}
                            locale/pt/LC_MESSAGES/django.po {% trans "for Portuguese and use the commands" %}:
                        <pre>
                django-admin.py makemessages -l pt
                django-admin.py compilemessages</pre>
                        </p>

                        <p>{% trans "Afterwards make the following changes in " %}
                            <a href="http://vision.ufabc.edu.br/static/_settings.env">_settings.env</a>:
                        <pre>
                LANGUAGE_CODE = 'pt-br'
                TIME_ZONE = 'America/Sao_Paulo'</pre>
                        {% trans "Please see 'locale' folder for other languages" %};
                        </p>
                    </li>
                    <li>
                        <p>{% trans "AI Exams Module: individual exams based on the students and the class history" %};</p>
                    </li>
                    <li>
                        <p>{% trans "AI Students Module: evaluation of how the weigh questions in order to show the skills and abilities of each student" %};</p>
                    </li>
                    <li>
                        <p>{% trans "Use of blockchain to validate exams, history and other features" %};</p>
                    </li>
                    <li>
                        <p>{% trans "Inclusion of facial recognition in the QR Code of the exams" %};</p>
                    </li>
                    <li>
                        <p>{% trans "Improve of Item Response Theory;  " %};</p>
                    </li>
                                        <li>
                        <p>{% trans "Use Markdown to describe questions and send exams or activities to students" %}.</p>
                    </li>


                </ol>

                <hr>

                <p><h5>{% trans "Versions" %}</h5></p>


                <ul>
                    <li>
                        <p><strong>webMCTest 1.0 (MCTest 5.0)</strong></p>
                        <ul>
                            <li>{% trans "August 2018" %}</li>
                            <li>{% trans "Multiple choice test model in QR Code itself" %}</li>
                        </ul>
                    </li>
                    <p></p>
                    <li>
                        <p><strong>webMCTest 1.1</strong></p>
                        <ul>
                            <li>{% trans "August 2019" %}</li>
                            <li>{% trans "New graphical interfaces" %}</li>
                            <li>{% trans "The multiple-choice test template is now stored on the server" %}</li>
                        </ul>
                    </li>
                    <p></p>
                    <li>
                        <p><strong>webMCTest 1.2</strong></p>
                        <ul>
                            <li>{% trans "grant #2018/23561-1, São Paulo Research Foundation (FAPESP)" %}</li>
                            <li>{% trans "Title: A universal system for generation and correction automatic of parametrized questions" %}</li>
                            <li>01/09/2019 - 31/08/2021</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}